#!/usr/bin/php
<?php

include('miner.inc.php');
include('settings.inc.php');


if(empty($settings['donateEnable']) || !$settings['donateEnable']){
	exit;
}

if (date('H') <> 12) {
	exit;
}

//$poolAddress = 'stratum+tcp://stratum.btcguild.com:3333';
//$poolUser = 'MinePeon_Donate';
//$poolPass = 'MinePeon_Donate';

$poolAddress = 'stratum+tcp://us.ozco.in:3333';
$poolUser = 'minepeon.donate';
$poolPass = 'donate';

// Load donateAmount or keep default of 15
$donateAmount = 15;
if(empty($settings['donateAmount'])){
	$donateAmount = $settings['donateAmount'];
}

// Let everyone know donation is initiated
$settings['donateActive'] = true;
writeSettings($settings);

// Append donatepool
cgminer("addpool",$poolAddress . "," . $poolUser . "," . $poolPass);

// Sleep for 5 secconds to avoid monitor scripts
// Also give miner time to connect to eligius
sleep(5);

// Look for the donatePool and give it priority
$pool = findDonatePool($poolUser);
cgminer('switchpool',$pool);

// Donate time!
sleep($settings['donateAmount'] * 60);

// Look for the donatePool and disable it before removing it
$pool = findDonatePool($poolUser);
cgminer('disablepool',$pool);
cgminer('removepool',$pool);

// Let everyone know donation ended
$settings['donateActive'] = false;
writeSettings($settings);


function findDonatePool($addr){
  $pools = cgminer('pools','')['POOLS'];
  $donatePool = -1;
  foreach ($pools as $k => $v) {
    if(isset($v['User']) && $v['User']==$addr){
      $donatePool = $k;
    }
  }
  return $donatePool;
}

?>