#!/usr/bin/php
<?php

include('miner.inc.php');
include('settings.inc.php');

if (isset($argv[1])) {
    
    echo "Arg    : " . $argv[1] . "\n\r";
    echo "Enabled: " . $settings['donateEnable'] . "\n\r";
    echo "Ammount: " . $settings['donateAmount'] . "\n\r";
}



if ($settings['donateEnable']) {
    
    if (date('H') == 12) {
        
        $miner    = "/opt/minepeon/etc/miner.conf";
        $donate   = "/opt/minepeon/etc/miner.conf.donate";
        $original = "/opt/minepeon/etc/miner.conf.orig";
        
        // Take your miner info and backup
        copy($miner, $original);
        
        // Sleep for 30 secconds to avoid monitor scripts
        sleep(30);
        
        $settings['donateActive'] = true;
        writeSettings($settings);
        
        // Restart using donation pools
        copy($donate, $miner);
        
        sleep(5);
        
        exec("/usr/bin/killall cgminer");
        exec("/usr/bin/killall bfgminer");
        
        sleep(60);
        
        // Copy back the normal pools
        
        copy($original, $miner);
        
        // Switch back to your pools after x minutes
        
        sleep(($settings['donateAmount'] * 60) - 65);
        
        exec("/usr/bin/killall cgminer");
        exec("/usr/bin/killall bfgminer");
        
        sleep(60);
        
        $settings['donateActive'] = false;
        writeSettings($settings);
        
    }
}