#!/usr/bin/php 
<?php

include('settings.inc.php');

$metric  = 'temp';
$RRDFILE = $metric . '.rrd';
$RRDPATH = '/opt/minepeon/var/rrd/';
$RRD     = $RRDPATH . $RRDFILE;

if (!file_exists($RRD)) {

	$options = array(
		"--step", "300",        
		"--start", "-12 months",    
		"DS:" . $metric . ":GAUGE:600:0:U",
		"RRA:AVERAGE:0.5:1:288",
		"RRA:AVERAGE:0.5:12:168",
		"RRA:AVERAGE:0.5:228:365"
	);

	rrd_create($RRD, $options);
	// echo rrd_error();
}



$command = round(exec('cat /sys/class/thermal/thermal_zone0/temp') / 1000, 2);

$result = time() . ':' . $command;

$update = array(
	$result
);


$ret = rrd_update($RRD, $update);

