#!/usr/bin/php
<?php

require('settings.inc.php');
require('miner.inc.php');

$datetime = date("Y-m-d H:i:s");

$db = new PDO('sqlite:/opt/minepeon/var/sql/summary.db');

$return = cgminer("summary", "");

$PiTemperature = round(exec('cat /sys/class/thermal/thermal_zone0/temp') / 1000, 2);



$sql = 'INSERT INTO "summary" ("When","Description","MHSav","MHS5s","FoundBlocks","Getworks","Accepted","Rejected","HardwareErrors","Utility","Discarded","Stale","GetFailures","LocalWork","RemoteFailures","NetworkBlocks","TotalMH","Diff1Work","WorkUtility","DifficultyAccepted","DifficultyRejected","DifficultyStale","BestShare","DeviceHardware%","DeviceRejected%","PoolRejected%","PoolStale%","PiTemperature", "datetime") 
	VALUES ("' .
	$return["STATUS"][0]["When"] . '", "' .
	$return["STATUS"][0]["Description"] . '", "' .
	$return["SUMMARY"][0]["MHSav"] . '", "' .
	$return["SUMMARY"][0]["MHS5s"] . '", "' .
	$return["SUMMARY"][0]["FoundBlocks"] . '", "' .
	$return["SUMMARY"][0]["Getworks"] . '", "' .
	$return["SUMMARY"][0]["Accepted"] . '", "' .
	$return["SUMMARY"][0]["Rejected"] . '", "' .
	$return["SUMMARY"][0]["HardwareErrors"] . '", "' .
	$return["SUMMARY"][0]["Utility"] . '", "' .
	$return["SUMMARY"][0]["Discarded"] . '", "' .
	$return["SUMMARY"][0]["Stale"] . '", "' .
	$return["SUMMARY"][0]["GetFailures"] . '", "' .
	$return["SUMMARY"][0]["LocalWork"] . '", "' .
	$return["SUMMARY"][0]["RemoteFailures"] . '", "' .
	$return["SUMMARY"][0]["NetworkBlocks"] . '", "' .
	$return["SUMMARY"][0]["TotalMH"] . '", "' .
	$return["SUMMARY"][0]["Diff1Work"] . '", "' .
	$return["SUMMARY"][0]["WorkUtility"] . '", "' .
	$return["SUMMARY"][0]["DifficultyAccepted"] . '", "' .
	$return["SUMMARY"][0]["DifficultyRejected"] . '", "' .
	$return["SUMMARY"][0]["DifficultyStale"] . '", "' .
	$return["SUMMARY"][0]["BestShare"] . '", "' .
	$return["SUMMARY"][0]["DeviceHardware%"] . '", "' .
	$return["SUMMARY"][0]["DeviceRejected%"] . '", "' .
	$return["SUMMARY"][0]["PoolRejected%"] . '", "' .
	$return["SUMMARY"][0]["PoolStale%"] . '", "' .
	$PiTemperature . '", "' .
	$datetime . '")';
	
// echo $sql;

$db->exec($sql);
